[tool.poetry]
name = "bourbon"
version = "0.1.0"
description = ""
authors = ["Adam Kaewell <adam@kaewell.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13"
textual = "^3.0.1"
sqlmodel = "^0.0.24"


[tool.poetry.group.dev.dependencies]
textual-dev = "^1.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
